# -*- coding: utf-8 -*-
"""MN_Exercise_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_GDGq7k8hQc5DRSEHd691WvHDdtuCy4-

# Task 0. Dataset Preparation
"""

import matplotlib.pyplot as plt
import scipy.io
import pandas as pd
import numpy as np
from scipy.signal import butter, filtfilt

fl_plot_color = "#2ca02c"
ex_plot_color = "#d62728"

raw_dataset_path = './wrist_flexion_extension.mat'

mat = scipy.io.loadmat(raw_dataset_path)

print(type(mat))
print(mat.keys())

EMG_raw_ex = mat["EMG_raw_ex"]
df_EMG_ex = pd.DataFrame(EMG_raw_ex)
EMG_raw_fl = mat["EMG_raw_fl"]
df_EMG_fl = pd.DataFrame(EMG_raw_fl)
force_ex = mat["force_ex"]
df_force_ex = pd.DataFrame(force_ex, columns=["force_ex"])
force_fl = mat["force_fl"]
df_force_fl = pd.DataFrame(force_fl, columns=["force_fl"])
fsamp = float(mat["fsamp"][0, 0])

df_ex = pd.DataFrame(EMG_raw_ex.T, columns=[f"EMG {i+1}" for i in range(32)])
df_ex["force"] = force_ex
df_ex

df_fl = pd.DataFrame(EMG_raw_fl.T, columns=[f"EMG {i+1}" for i in range(32)])
df_fl["force"] = force_fl
df_fl

"""# Task 1. Data preprocessing & visualisation

## 1.1 Convert the force transducer signal to Newtons
"""

gravity = 9.81
conversion_factor = 0.1

col_force_fl = df_fl["force"]
col_force_fl = (col_force_fl * gravity) / conversion_factor

print(col_force_fl)

df_fl["force"] = col_force_fl

col_force_ex = df_ex["force"]
col_force_ex = (col_force_ex * gravity) / conversion_factor

print(col_force_ex)

df_ex["force"] = col_force_ex

"""## 1.2 Plot the force signal"""

force_fl_absolute = df_fl["force"].abs()
force_ex_absolute = df_ex["force"].abs()

time_fl = np.arange(len(force_fl_absolute)) / fsamp
time_ex = np.arange(len(force_ex_absolute)) / fsamp

fig, axes = plt.subplots(1, 2, figsize=(18, 5))

axes[0].plot(time_fl, force_fl_absolute, color=fl_plot_color)
axes[0].set_xlabel("Time [s]")
axes[0].set_ylabel("Force [N]")
axes[0].set_title("Flexion Force Signal")
axes[0].grid(True)

axes[1].plot(time_ex, force_ex_absolute, color=ex_plot_color)
axes[1].set_xlabel("Time [s]")
axes[1].set_ylabel("Force [N]")
axes[1].set_title("Extension Force Signal")
axes[1].grid(True)

plt.tight_layout()
plt.show()

"""## 1.3 Plot all EMG channels in mV over time"""

def plot_EMG_signals(df, is_flexion):
  time = np.arange(len(df)) / fsamp

  interspace = 5.0

  plot_color = fl_plot_color if is_flexion else ex_plot_color
  plot_title = "EMG Signals in Flexion Over Time" if is_flexion else "EMG Signals in Extension Over Time"

  columns = [col for col in df.columns if col.startswith("EMG")]
  plt.figure(figsize=(12, 20))

  for i, col in enumerate(columns):
      plt.plot(time, df[col] + i*interspace, color=plot_color)

  yticks = [i*interspace for i in range(len(columns))]
  plt.yticks(yticks, columns)

  plt.xlabel("Time [s]")
  plt.ylabel("EMG Channels [mV]")
  plt.title(plot_title)
  plt.grid(True)
  plt.tight_layout()
  plt.show()

plot_EMG_signals(df_fl, True)

plot_EMG_signals(df_ex, False)

"""## 1.4 Delete the channels from the EMG_raw signals that show strange behavior"""

df_fl = df_fl.drop(columns=["EMG 12", "EMG 13"])
df_ex = df_ex.drop(columns=["EMG 12"])

plot_EMG_signals(df_fl, True)

plot_EMG_signals(df_ex, False)

"""## 1.5 The EMG signals contain noise

### 1.5.1
"""

def butter_bandpass(lowcut, highcut, fs, order=4):
    nyq = 0.5 * fs
    low = lowcut / nyq
    high = highcut / nyq
    b, a = butter(order, [low, high], btype='band')
    return b, a

def apply_bandpass_filter(data, lowcut, highcut, fs, order=4):
    b, a = butter_bandpass(lowcut, highcut, fs, order=order)
    y = filtfilt(b, a, data)
    return y

channel_fl = "EMG 18"
unfiltered = df_fl[channel_fl]
filtered_fl = apply_bandpass_filter(unfiltered, lowcut=50, highcut=450, fs=fsamp)

time = np.arange(len(unfiltered)) / fsamp

plt.figure(figsize=(12, 4))
plt.plot(time, unfiltered, label="Unfiltered", alpha=0.4, color="black")
plt.plot(time, filtered_fl, label="Filtered", color=fl_plot_color)
plt.xlabel("Time [s]")
plt.ylabel("EMG [mV]")
plt.title(f"EMG Channel {channel_fl} in Flexion: Unfiltered vs Filtered")
plt.legend()
plt.grid(True)
plt.show()

channel_ex = "EMG 30"
unfiltered = df_ex[channel_ex]
filtered_ex = apply_bandpass_filter(unfiltered, lowcut=50, highcut=450, fs=fsamp)

time = np.arange(len(unfiltered)) / fsamp

plt.figure(figsize=(12, 4))
plt.plot(time, unfiltered, label="Unfiltered", alpha=0.4, color="black")
plt.plot(time, filtered_ex, label="Filtered", color=ex_plot_color)
plt.xlabel("Time [s]")
plt.ylabel("EMG [mV]")
plt.title(f"EMG Channel {channel_ex} in Extension: Unfiltered vs Filtered")
plt.legend()
plt.grid(True)
plt.show()

"""### 1.5.2

"""

unfiltered = df_fl[channel_fl].values

N = len(unfiltered)
freq = np.fft.rfftfreq(N, 1/fsamp)
fft_unfiltered = np.abs(np.fft.rfft(unfiltered)) / N
fft_filtered = np.abs(np.fft.rfft(filtered_fl)) / N

plt.figure(figsize=(12, 6))

plt.subplot(2, 1, 1)
plt.plot(freq, fft_unfiltered, color=fl_plot_color)
plt.title(f"FFT of Unfiltered EMG Channel {channel_fl} in Flexion")
plt.xlabel("Frequency [Hz]")
plt.ylabel("Amplitude")
plt.grid(True)

plt.subplot(2, 1, 2)
plt.plot(freq, fft_filtered, color='#1f77b4')
plt.title(f"FFT of Filtered EMG Channel {channel_fl} in Flexion")
plt.xlabel("Frequency [Hz]")
plt.ylabel("Amplitude")
plt.grid(True)

plt.tight_layout()
plt.show()

unfiltered = df_ex[channel_ex].values

N = len(unfiltered)
freq = np.fft.rfftfreq(N, 1/fsamp)
fft_unfiltered = np.abs(np.fft.rfft(unfiltered)) / N
fft_filtered = np.abs(np.fft.rfft(filtered_ex)) / N

plt.figure(figsize=(12, 6))

plt.subplot(2, 1, 1)
plt.plot(freq, fft_unfiltered, color=ex_plot_color)
plt.title(f"FFT of Unfiltered EMG Channel {channel_ex} in Extension")
plt.xlabel("Frequency [Hz]")
plt.ylabel("Amplitude")
plt.grid(True)

plt.subplot(2, 1, 2)
plt.plot(freq, fft_filtered, color='#1f77b4')
plt.title(f"FFT of Filtered EMG Channel {channel_ex} in Extension")
plt.xlabel("Frequency [Hz]")
plt.ylabel("Amplitude")
plt.grid(True)

plt.tight_layout()
plt.show()

"""## 1.6 Plot an exemplary channel of your choice

"""

force_signal = np.abs(df_fl["force"].values)

time = np.arange(len(filtered_fl)) / fsamp

fig, ax1 = plt.subplots(figsize=(12, 4))

color_emg = 'tab:blue'
ax1.set_xlabel("Time [s]")
ax1.set_ylabel("EMG [mV]", color=color_emg)
ax1.plot(time, filtered_fl, color=color_emg, label="Filtered EMG")
ax1.tick_params(axis='y', labelcolor=color_emg)

ax2 = ax1.twinx()
color_force = 'tab:red'
ax2.set_ylabel("Force [N]", color=color_force)
ax2.plot(time, force_signal, color=fl_plot_color, label="Force")
ax2.tick_params(axis='y', labelcolor=color_force)

fig.tight_layout()
plt.title(f"Filtered ({channel_fl}) and Force Signal in Flexion")
plt.show()

force_signal = np.abs(df_ex["force"].values)

time = np.arange(len(filtered_ex)) / fsamp

fig, ax1 = plt.subplots(figsize=(12, 4))

color_emg = 'tab:blue'
ax1.set_xlabel("Time [s]")
ax1.set_ylabel("EMG [mV]", color=color_emg)
ax1.plot(time, filtered_ex, color=color_emg, label="Filtered EMG")
ax1.tick_params(axis='y', labelcolor=color_emg)

ax2 = ax1.twinx()
color_force = 'tab:red'
ax2.set_ylabel("Force [N]", color=color_force)
ax2.plot(time, force_signal, color=ex_plot_color, label="Force")
ax2.tick_params(axis='y', labelcolor=color_force)

fig.tight_layout()
plt.title(f"Filtered ({channel_ex}) and Force Signal in Exntension")
plt.show()

"""# Task 2. Force steadiness"""

def calculate_CV(df):
  force_signal = np.abs(df["force"].values)

  start_sec = 7
  end_sec = 19

  start_idx = int(start_sec * fsamp)
  end_idx = int(end_sec * fsamp)

  force_plateau = force_signal[start_idx:end_idx]


  mean_force = np.mean(force_plateau)
  std_force = np.std(force_plateau)

  cv = (std_force / mean_force) * 100
  return cv

CV_fl = calculate_CV(df_fl)
CV_ex = calculate_CV(df_ex)

print(f"Task 2.1: Wrist Flexion, CV = {CV_fl:.2f} %")
print(f"Task 2.1: Wrist Extension, CV = {CV_ex:.2f} %")

"""# Task 3. Rate of force development

## 3.1
"""

def calculate_RFD(force):
  window_ms = 1000
  window_samples = int(window_ms / 1000 * fsamp)
  rfd_list = []

  for start in range(0, len(force) - window_samples):
      end = start + window_samples
      delta_f = force[end] - force[start]
      delta_t = window_samples / fsamp
      rfd = delta_f / delta_t
      rfd_list.append(rfd)

  rfd_array = np.array(rfd_list)
  return rfd_array

rfd_fl = calculate_RFD(df_fl["force"].abs())
rfd_ex = calculate_RFD(df_ex["force"].abs())

print("Peak RFD in Flexion", np.max(rfd_fl), "N/s")
print("Mean RFD in Flexion", np.mean(rfd_fl), "N/s")

print("Peak RFD in Extension", np.max(rfd_ex), "N/s")
print("Mean RFD in Extension", np.mean(rfd_ex), "N/s")

"""## 3.2"""

time_rfd = np.arange(rfd_fl.size) / fsamp

plt.figure(figsize=(12, 4))
plt.plot(time_rfd, rfd_fl, color=fl_plot_color)
plt.xlabel("Time [s]")
plt.ylabel("RFD [N/s]")
plt.title("Rate of Force Development (RFD) over Time in Flexion")
plt.grid(True)
plt.tight_layout()
plt.show()

time_rfd = np.arange(rfd_ex.size) / fsamp

plt.figure(figsize=(12, 4))
plt.plot(time_rfd, rfd_ex, color=ex_plot_color)
plt.xlabel("Time [s]")
plt.ylabel("RFD [N/s]")
plt.title("Rate of Force Development (RFD) over Time in Extension")
plt.grid(True)
plt.tight_layout()
plt.show()

"""# Task 4. Root-Mean-Square (RMS) of EMG

## 4.1
"""

emg_columns = [col for col in df_fl.columns if col.startswith("EMG")]

emg_filtered_df = df_fl[emg_columns].copy()

for col in emg_columns:
    emg_filtered_df[col] = apply_bandpass_filter(
        df_fl[col].values, lowcut=50, highcut=450, fs=fsamp
    )

emg_filtered = emg_filtered_df

emg_avg_fl = emg_filtered.mean(axis=1).values
print(emg_avg_fl)

emg_columns = [col for col in df_ex.columns if col.startswith("EMG")]

emg_filtered_df = df_ex[emg_columns].copy()

for col in emg_columns:
    emg_filtered_df[col] = apply_bandpass_filter(
        df_ex[col].values, lowcut=50, highcut=450, fs=fsamp
    )

emg_filtered = emg_filtered_df

emg_avg_ex = emg_filtered.mean(axis=1).values
print(emg_avg_ex)

"""## 4.2

"""

def moving_rms(signal, window_samples):
    squared = signal ** 2
    kernel = np.ones(window_samples) / window_samples
    rms = np.sqrt(np.convolve(squared, kernel, mode="same"))
    return rms

window_ms = 400
window_samples = int(window_ms / 1000 * fsamp)

rms_emg_fl = moving_rms(emg_avg_fl, window_samples)

time_rms = np.arange(len(rms_emg_fl)) / fsamp

plt.figure(figsize=(12, 4))
plt.plot(time_rms, rms_emg_fl, color=fl_plot_color)
plt.xlabel("Time [s]")
plt.ylabel("RMS EMG [mV]")
plt.title("Task 4.2: RMS of Averaged EMG Signal in Flexion")
plt.grid(True)
plt.tight_layout()
plt.show()

window_ms = 400
window_samples = int(window_ms / 1000 * fsamp)

rms_emg_ex = moving_rms(emg_avg_ex, window_samples)

time_rms = np.arange(len(rms_emg_ex)) / fsamp

plt.figure(figsize=(12, 4))
plt.plot(time_rms, rms_emg_ex, color=ex_plot_color)
plt.xlabel("Time [s]")
plt.ylabel("RMS EMG [mV]")
plt.title("Task 4.2: RMS of Averaged EMG Signal in Flexion")
plt.grid(True)
plt.tight_layout()
plt.show()

"""## 4.3"""

RMS = rms_emg_fl
force = df_fl["force"].abs()

RMS_norm_fl = (RMS - np.min(RMS)) / (np.max(RMS) - np.min(RMS))
Force_norm_fl = (force - np.min(force)) / (np.max(force) - np.min(force))

r = np.corrcoef(RMS_norm_fl, Force_norm_fl)[0, 1]

plt.figure(figsize=(12, 8))
plt.scatter(RMS_norm_fl, Force_norm_fl, color=fl_plot_color)
plt.xlabel("Normalized RMS")
plt.ylabel("Normalized Force")
plt.title(f"Task 4.3: Wrist Flexion – Correlation between RMS and Force – r = {r:.3f}")
plt.grid(True)
plt.show()

RMS = rms_emg_ex
force = df_ex["force"].abs()

RMS_norm_ex = (RMS - np.min(RMS)) / (np.max(RMS) - np.min(RMS))
Force_norm_ex = (force - np.min(force)) / (np.max(force) - np.min(force))

r = np.corrcoef(RMS_norm_ex, Force_norm_ex)[0, 1]

plt.figure(figsize=(12, 8))
plt.scatter(RMS_norm_ex, Force_norm_ex, color=ex_plot_color)
plt.xlabel("Normalized RMS")
plt.ylabel("Normalized Force")
plt.title(f"Task 4.3: Wrist Extension – Correlation between RMS and Force – r = {r:.3f}")
plt.grid(True)
plt.show()